# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: serverless
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  # stage: dev
  # region: 'us-west-2'

  # you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  patterns:
#    - '!exclude-me.rb'
#    - '!exclude-me-dir/**'
#    - include-me.rb
#    - include-me-dir/**

plugins:
  - serverless-dynamodb-local

functions:
  get_data:
    handler: handler.get_data
    events:
      - schedule: rate(10 minutes)
  read_data:
    handler: handler.read_data
#    events:

# you can add CloudFormation resource templates here
resources:
  Resources:
    fundTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: info_fund
        AttributeDefinitions:
          - AttributeName: info
            AttributeType: S
          - AttributeName: fund_id
            AttributeType: N
        KeySchema:
          - AttributeName: info
            KeyType: HASH
          - AttributeName: fund_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10

    PCOTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: clientes_pco
        AttributeDefinitions:
          - AttributeName: nome
            AttributeType: S
          - AttributeName: idCliente
            AttributeType: N
        KeySchema:
          - AttributeName: nome
            KeyType: HASH
          - AttributeName: idCliente
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    # rescueTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:

#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
